# Matrix Multiplication

Given a simple 3x3 image represented as a matrix, where each cell represents a pixel's intensity, and a 3x3 
transformation matrix, perform matrix multiplication to transform the image.

In [4]:
import numpy as np

# Original Image Matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Transformation Matrix
B = np.array([[0, 1, 0],
              [-1, 0, 0],
              [0, 0, 1]])

# Perform Matrix Multiplication
Transformed_Image = np.dot(A, B)
print(Transformed_Image)

[[-2  1  3]
 [-5  4  6]
 [-8  7  9]]


Given a plain text message and a key matrix, encode the message using matrix multiplication. Convert the message to numerical 
form using ASCII values and arrange it in a matrix where each number represents a character. Multiply the message matrix by the key 
matrix to get the encrypted message matrix.

In [5]:
# Message Matrix (ASCII Values of 'ABC')
E = np.array([[65, 66, 67]])

# Key Matrix
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Perform matrix multiplication to encrypt the message
Encrypted_Message = np.dot(E, F)
print(Encrypted_Message)

[[ 798  996 1194]]
