# System of linear equations

Three movies were screened in a cinema over a weekend: "Action Adventure", "Romantic Comedy", and "Sci-fi Thriller". The individual ticket prices for these movies are x, y, and z dollars respectively. However, you've only been given the following pieces of information:

 - 700 tickets were sold for "Action Adventure" and 300 tickets for "Romantic Comedy", collecting a total revenue of 7,000.
 - 500 tickets were sold for "Romantic Comedy" and 500 for "Sci-fi Thriller", with a combined revenue of  6,000.
 - "Action Adventure" and "Sci-fi Thriller" together sold 1000 tickets and generated a revenue of 9,000.
 

Define the coefficient matrix A and the constant matrix B from your system of equations.

In [4]:
import numpy as np

# Define the coefficient matrix A and the constant matrix B
A = np.array([
    [700, 300, 0],
    [0, 500, 500],
    [700, 0, 300]
])

B = np.array([7000, 6000, 9000])

Calculate the determinant of the coefficient matrix A. If the determinant is non-zero, 
proceed to the next step. If it is zero, indicate that the inverse of A does not exist and discuss the implications.

In [5]:
 #Calculate the determinant of matrix A
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

Determinant of A: 209999999.99999928


Calculate the inverse of matrix A if it exists. 

In [6]:
# Check if determinant is non-zero and calculate the inverse if it is
if det_A != 0:
    A_inv = np.linalg.inv(A)
    print(f"Inverse of A: \n{A_inv}")
else:
    A_inv = None
    print("Inverse of A does not exist.")

Inverse of A: 
[[ 0.00071429 -0.00042857  0.00071429]
 [ 0.00166667  0.001      -0.00166667]
 [-0.00166667  0.001       0.00166667]]


Use the inverse of matrix A to solve for the variable matrix \(X\) representing the ticket prices for the movies, i.e., 
x,y,z. If the inverse does not exist, discuss the implications on the system of equations.


In [7]:
if A_inv is not None:
    X = np.dot(A_inv, B)
    print(f"Ticket prices: x = ${X[0]:.2f}, y = ${X[1]:.2f}, z = ${X[2]:.2f}")
else:
    X = None
    print("Cannot solve for ticket prices as A is singular.")


Ticket prices: x = $8.86, y = $2.67, z = $9.33
